package com.toester.toester

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { EN, CS }

val LocalLanguage = compositionLocalOf { AppLanguage.EN }
val LocalToggleLanguage = compositionLocalOf<() -> Unit> { {} }

data class Strings(
    // Landing
    val hi: String,
    val streak: String,
    val days: String,
    val dailyQuests: String,
    val myProfile: String,
    val uniSubjects: String,

    // UniSubjects
    val teacher: String,
    val open: String,
    val addSubject: String,
    val backToLanding: String,

    // AddSubject
    val addNewSubject: String,
    val subjectName: String,
    val teacherLabel: String,
    val subjectId: String,
    val saveSubject: String,

    // Profile
    val profile: String,
    val changePhoto: String,
    val uploadPhoto: String,
    val stats: String,
    val level: String,
    val xpToLevel: String, // "$xp XP to Level $lvl"
    val totalXp: String,
    val xpProgressTitle: String,
    val editProfile: String,
    val nickname: String,
    val saveChanges: String,
    val leaderboard: String,
    val thisWeek: String,
    val noFriends: String,
    val you: String,
    val addFriend: String,
    val userId: String,
    val send: String,
    val sentRequests: String,
    val pending: String,
    val incomingRequests: String,
    val accept: String,
    val decline: String,
    val totalXpLabel: String,
    val thisWeekLabel: String,

    // SubjectDetail
    val subjectQuests: String,
    val noQuestsToday: String,
    val lecturesPdf: String,
    val addPdfLecture: String,
    val backToSubjects: String,
    val selectPdfLecture: String,

    // PdfViewer
    val close: String,
    val pdfNotAvailable: String,

    // Quests
    val completeQuest: String,
    val questCompleted: String,
)

val EnStrings = Strings(
    hi = "Hi",
    streak = "Streak",
    days = "days",
    dailyQuests = "Daily quests",
    myProfile = "My profile",
    uniSubjects = "Uni subjects",
    teacher = "Teacher",
    open = "Open",
    addSubject = "Add Subject",
    backToLanding = "Back to landing",
    addNewSubject = "Add New Subject",
    subjectName = "Subject Name",
    teacherLabel = "Teacher",
    subjectId = "Subject ID (e.g. math101)",
    saveSubject = "Save Subject",
    profile = "Profile",
    changePhoto = "Change photo",
    uploadPhoto = "Upload photo",
    stats = "Stats",
    level = "Level",
    xpToLevel = "XP to Level",
    totalXp = "Total XP",
    xpProgressTitle = "XP Progress (last 14 days)",
    editProfile = "Edit Profile",
    nickname = "Nickname",
    saveChanges = "Save changes",
    leaderboard = "Leaderboard",
    thisWeek = "This week",
    noFriends = "No friends yet – send a request below!",
    you = "(you)",
    addFriend = "Add a friend",
    userId = "User ID",
    send = "Send",
    sentRequests = "Sent requests",
    pending = "pending",
    incomingRequests = "Incoming requests",
    accept = "Accept",
    decline = "Decline",
    totalXpLabel = "total XP",
    thisWeekLabel = "this week",
    subjectQuests = "Subject quests",
    noQuestsToday = "No quests for today. Check back tomorrow!",
    lecturesPdf = "Lectures (PDF)",
    addPdfLecture = "Add PDF Lecture",
    backToSubjects = "Back to subjects",
    selectPdfLecture = "Select PDF Lecture",
    close = "Close",
    pdfNotAvailable = "PDF data not available for",
    completeQuest = "Complete",
    questCompleted = "Done!",
)

val CsStrings = Strings(
    hi = "Ahoj",
    streak = "Série",
    days = "dní",
    dailyQuests = "Denní úkoly",
    myProfile = "Můj profil",
    uniSubjects = "Předměty",
    teacher = "Vyučující",
    open = "Otevřít",
    addSubject = "Přidat předmět",
    backToLanding = "Zpět na úvod",
    addNewSubject = "Přidat nový předmět",
    subjectName = "Název předmětu",
    teacherLabel = "Vyučující",
    subjectId = "ID předmětu (např. math101)",
    saveSubject = "Uložit předmět",
    profile = "Profil",
    changePhoto = "Změnit fotku",
    uploadPhoto = "Nahrát fotku",
    stats = "Statistiky",
    level = "Úroveň",
    xpToLevel = "XP do úrovně",
    totalXp = "Celkové XP",
    xpProgressTitle = "Průběh XP (posledních 14 dní)",
    editProfile = "Upravit profil",
    nickname = "Přezdívka",
    saveChanges = "Uložit změny",
    leaderboard = "Žebříček",
    thisWeek = "Tento týden",
    noFriends = "Zatím žádní přátelé – pošli žádost níže!",
    you = "(ty)",
    addFriend = "Přidat přítele",
    userId = "ID uživatele",
    send = "Odeslat",
    sentRequests = "Odeslané žádosti",
    pending = "čeká",
    incomingRequests = "Příchozí žádosti",
    accept = "Přijmout",
    decline = "Odmítnout",
    totalXpLabel = "celkové XP",
    thisWeekLabel = "tento týden",
    subjectQuests = "Úkoly předmětu",
    noQuestsToday = "Žádné úkoly pro dnešek. Zkus to zítra!",
    lecturesPdf = "Přednášky (PDF)",
    addPdfLecture = "Přidat PDF přednášku",
    backToSubjects = "Zpět na předměty",
    selectPdfLecture = "Vybrat PDF přednášku",
    close = "Zavřít",
    pdfNotAvailable = "PDF data nejsou dostupná pro",
    completeQuest = "Splnit",
    questCompleted = "Hotovo!",
)

val LocalStrings = compositionLocalOf { EnStrings }

